### ISSUE TITLE
Configs don't save

### ISSUE THREAD

**Issue by FleetOfWarships** [NitrinaxValheim/CustomizedBronze#1]
Whenever I make a custom recipe and set it as such the settings don't save when I click the save button as the next time I open the config everything is back to defaults.

**Comment by Nitrinax** [comment]
okay send me your settings please

BepInEx version
Jotunn version
Valheim version
.NET Framework version

**Comment by FleetOfWarships** [comment]
Apologies for the delay, school just started. The problem has been resolved, the profile I was using on r2modman was corrupted or something, I made a new one and the config saves fine, both in the mod manager and via mod settings in-game.

**Comment by Nitrinax** [comment]
okay, closed

**Comment by NitrinaxValheim** [comment]
okay closed
