### ISSUE TITLE
Valheim 0.217.25 not working

### ISSUE THREAD

**Issue by hikingmetalpunk** [NitrinaxValheim/CustomizedBronze#2]
With 0.217.25 it seems whether I set the config to 'realistic' or 'custom' the recipe doesn't take effect. I'm afraid I only just came back to the game after a long break so I can't say if previous versions also had this effect.

Unclear if mods in this game can conflict the way they do in say skyrim or fallout 3/nv/4, I'm using valheim+ and a couple others.

Using r2modman 3.1.44,
bepinex 5.4.2200
jotun 2.1.4.5
.NET framework 4.8

**Comment by NitrinaxValheim** [comment]
Thanks for the message, I'll look into it. Can you post all the error messages regarding this mod here?

**Comment by NitrinaxValheim** [comment]
okay, i uploaded a new version

**Comment by hikingmetalpunk** [comment]
Sorry, was asleep when you updated -- I'll try the new version when I can and report back.

**Comment by hikingmetalpunk** [comment]
Ok! All working here now.  I did have some issues with the config file for some reason, I had to change it to Custom, then back to Realistic before it would 'stick', but seems to be working fine now.

**Comment by NitrinaxValheim** [comment]
This was because identifiers were changed within the configuration file. I had forgotten to point this out.

**Comment by NitrinaxValheim** [comment]
solved

**Comment by NitrinaxValheim** [comment]
and closed
